export const permissions = {
  people: {
    read: "people.read",
    invite: "people.invite",
    edit: "people.edit",
  },
  expense: {
    read: "expense.read",
    create: "expense.create",
    approve: "expense.approve",
    reject: "expense.reject",
  },
  bill: {
    read: "bill.read",
    create: "bill.create",
    approve: "bill.approve",
  },
  payment: {
    create: "payment.create",
    release: "payment.release",
  },
  treasury: {
    transferCreate: "treasury.transfer.create",
    transferApprove: "treasury.transfer.approve",
    transferRelease: "treasury.transfer.release",
  },
} as const;

export const ALL_PERMISSIONS = [
  "people.read",
  "people.invite",
  "people.edit",
  "roles.assign",
  "card.read",
  "card.issue",
  "card.freeze",
  "fund.create",
  "spend_program.manage",
  "spend_request.create",
  "spend_request.approve",
  "expense.read",
  "expense.create",
  "expense.approve",
  "reimbursement.create",
  "reimbursement.approve",
  "reimbursement.pay",
  "bill.create",
  "bill.approve",
  "payment.create",
  "payment.release",
  "procurement.request",
  "travel.book",
  "travel.approve",
  "budget.manage",
  "report.read",
  "accounting.read",
  "accounting.code",
  "accounting.sync",
  "treasury.transfer.create",
  "report.read",
  "audit.read",
] as const;

export const scopes = [
  "SELF",
  "ASSIGNED",
  "DIRECT_REPORTS",
  "TEAM",
  "DEPARTMENT",
  "LOCATION",
  "ENTITY",
  "MULTI_ENTITY",
  "ORGANIZATION",
  "VENDOR_SCOPED",
  "CUSTOM_SCOPE",
] as const;
