export const permissions = {
  people: {
    read: "people.read",
    invite: "people.invite",
    edit: "people.edit",
  },
  expense: {
    read: "expense.read",
    create: "expense.create",
    approve: "expense.approve",
  },
  bill: {
    read: "bill.read",
    create: "bill.create",
    approve: "bill.approve",
  },
  payment: {
    create: "payment.create",
    release: "payment.release",
  },
  treasury: {
    transferCreate: "treasury.transfer.create",
    transferApprove: "treasury.transfer.approve",
    transferRelease: "treasury.transfer.release",
  },
} as const;

/** Canonical named permission keys (excludes Owner wildcard `*`). */
export const ALL_PERMISSIONS = [
  "people.read",
  "people.invite",
  "people.edit",
  "roles.assign",
  "card.read",
  "card.issue",
  "card.freeze",
  "fund.create",
  "spend_program.manage",
  "spend_request.create",
  "spend_request.approve",
  "expense.read",
  "expense.create",
  "expense.approve",
  "reimbursement.create",
  "reimbursement.approve",
  "reimbursement.pay",
  "bill.read",
  "bill.create",
  "bill.approve",
  "payment.create",
  "payment.release",
  "payment_run.manage",
  "procurement.request",
  "procurement.review",
  "po.create",
  "travel.book",
  "travel.approve",
  "vendor.read",
  "vendor.create",
  "vendor.bank_details.manage",
  "accounting.read",
  "accounting.code",
  "accounting.sync",
  "treasury.transfer.create",
  "treasury.transfer.approve",
  "treasury.transfer.release",
  "report.read",
  "budget.manage",
  "audit.read",
] as const;

export const scopes = [
  "SELF",
  "ASSIGNED",
  "DIRECT_REPORTS",
  "TEAM",
  "DEPARTMENT",
  "LOCATION",
  "ENTITY",
  "MULTI_ENTITY",
  "ORGANIZATION",
  "VENDOR_SCOPED",
  "CUSTOM_SCOPE",
] as const;

export {
  ROLE_CRUD,
  ROLE_PAGE_MODULES,
  ROLE_SCOPES,
  SYSTEM_ROLE_NAMES,
  assertValidMatrixSelection,
  groupModulesBySection,
  isCapabilityAvailable,
  isSystemRoleName,
  moduleById,
  permissionKeysFromSelection,
  selectionFromPermissionKeys,
  type PageCapability,
  type PageGrantSelection,
  type RoleCrud,
  type RoleMatrixSelection,
  type RolePageModule,
  type RoleScope,
} from "./role-matrix";
