"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FormEvent, useEffect, useState } from "react";
import { PageHeader, StatusBadge } from "@finance/design-system";
import { api } from "@/lib/api";
type Program = { id: string; name: string; description: string; maxAmount: string | number; currency: string; status: string; merchantLockDefault?: string; allowedMccsDefault?: string; perTransactionLimitDefault?: string; velocityMaxAmountDefault?: string; velocityMaxCountDefault?: number };
export default function ProgramDetailPage() { const { id } = useParams<{ id: string }>(); const client = useQueryClient(); const detail = useQuery({ queryKey: ["program", id], queryFn: () => api.get<Program>(`/spend-programs/${id}`) }); const [form, setForm] = useState({ name: "", description: "", maxAmount: "", currency: "USD", merchantLockDefault: "", allowedMccsDefault: "", perTransactionLimitDefault: "", velocityMaxAmountDefault: "", velocityMaxCountDefault: "" }); const [message, setMessage] = useState(""); useEffect(() => { if (detail.data) setForm({ name: detail.data.name, description: detail.data.description, maxAmount: String(detail.data.maxAmount), currency: detail.data.currency, merchantLockDefault: detail.data.merchantLockDefault ?? "", allowedMccsDefault: detail.data.allowedMccsDefault ?? "", perTransactionLimitDefault: detail.data.perTransactionLimitDefault ?? "", velocityMaxAmountDefault: detail.data.velocityMaxAmountDefault ?? "", velocityMaxCountDefault: String(detail.data.velocityMaxCountDefault ?? "") }); }, [detail.data]); const action = useMutation({ mutationFn: ({ name, body }: { name: string; body?: object }) => api.post(`/spend-programs/${id}/${name}`, body ?? {}), onSuccess: (_result, input) => { setMessage(`${input.name} completed.`); void client.invalidateQueries({ queryKey: ["program", id] }); } }); function submit(event: FormEvent) { event.preventDefault(); action.mutate({ name: "update", body: form }); } if (!detail.data) return <p className="muted">Loading program…</p>; return <div className="stack-lg"><div className="resource-heading"><PageHeader title={detail.data.name} subtitle={`${detail.data.currency} ${detail.data.maxAmount}`} /><Link className="btn btn-ghost" href="/app/spend/programs">Back</Link></div><p><StatusBadge status={detail.data.status} /></p>{message && <p className="notice">{message}</p>}{action.error && <p className="error">{action.error.message}</p>}<section className="panel"><h2>Edit controls</h2><form className="record-form" onSubmit={submit}>{Object.entries(form).map(([key,value]) => <label key={key}>{key.replace(/([A-Z])/g," $1")}<input className="input" value={value} disabled={key === "currency"} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}<button className="btn btn-primary">Save changes</button></form></section>{detail.data.status === "ACTIVE" && <button className="btn btn-danger" onClick={() => window.confirm("Deactivate this spend program?") && action.mutate({ name: "deactivate" })}>Deactivate</button>}</div>; }
