"use client";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { PageHeader, StatusBadge } from "@finance/design-system";
import { api } from "@/lib/api";
type Candidate = { id: string; merchant: string; amount: string | number; currency: string; createdAt: string; transactionId: string | null; status: string; score: number; reasons: string[]; employee?: { firstName: string; lastName: string; email: string } };
type Detail = { receipt: { merchantGuess: string | null; amountGuess: string | number | null; matchStatus: string }; candidates: Candidate[] };
export default function ReceiptLinkPage() { const { id } = useParams<{ id: string }>(); const router = useRouter(); const [search, setSearch] = useState(""); const detail = useQuery({ queryKey: ["receipt-candidates", id, search], queryFn: () => api.get<Detail>(`/receipts/${id}${search ? `?q=${encodeURIComponent(search)}` : ""}`) }); const link = useMutation({ mutationFn: (expenseId: string) => api.post(`/receipts/${id}/link`, { expenseId }), onSuccess: (_result, expenseId) => router.push(`/app/expenses/${expenseId}`) }); return <div className="stack-lg"><div className="resource-heading"><PageHeader title="Link receipt" subtitle="Suggested matches are deterministic from merchant, amount, date, transaction, expense, and employee context." /><Link className="btn btn-ghost" href="/app/expenses/receipts">Back</Link></div><section className="panel"><div className="form-grid"><label>Search candidates<input className="input" placeholder="Employee, merchant, amount, transaction, or expense" value={search} onChange={(e) => setSearch(e.target.value)} /></label></div><p className="muted">Receipt guess: {detail.data?.receipt.merchantGuess ?? "unknown merchant"} · {String(detail.data?.receipt.amountGuess ?? "unknown amount")}</p>{link.error && <p className="error">{link.error.message}</p>}<ul className="plain-list">{(detail.data?.candidates ?? []).map((candidate) => <li key={candidate.id}><strong>{candidate.merchant}</strong> · {candidate.currency} {String(candidate.amount)} · {candidate.employee ? `${candidate.employee.firstName} ${candidate.employee.lastName}` : "Employee"} · <StatusBadge status={candidate.status} /><div className="muted">Suggested score {candidate.score}{candidate.reasons.length ? ` · ${candidate.reasons.join(", ")}` : ""} · {new Date(candidate.createdAt).toLocaleDateString()} {candidate.transactionId ? `· transaction ${candidate.transactionId.slice(0,8)}` : ""}</div><button className="btn btn-primary" disabled={link.isPending} onClick={() => link.mutate(candidate.id)}>Link to this expense</button></li>)}</ul></section></div>; }
