import fs from 'node:fs';import {chromium} from 'playwright';const base='http://localhost:3122',output=[];const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext(),page=await context.newPage();
async function call(path,data,token){const r=await context.request.post(base+'/api/v1'+path,{data,headers:token?{authorization:'Bearer '+token}:{}});const b=await r.json();if(!r.ok())throw new Error(JSON.stringify(b));return b.data;}
try{const admin=(await call('/identity/login',{workspace:'acme',email:'admin@acme.test',password:'password123'})).token;const roles=await(await context.request.get(base+'/api/v1/rbac',{headers:{authorization:'Bearer '+admin}})).json();const email='qa.auth.'+Date.now()+'@acme.test';const invited=await call('/people',{email,firstName:'QA',lastName:'Auth',roleId:roles.data[0].id},admin);
await page.goto(base+invited.activationPath,{waitUntil:'networkidle'});await page.getByLabel('Workspace',{exact:true}).fill('acme');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('New password',{exact:true}).fill('ActivationPass123');await page.getByLabel('Confirm password',{exact:true}).fill('ActivationPass123');const activatedResponse=page.waitForResponse(r=>r.url().includes('/identity/activate'),{timeout:20000});await page.getByRole('button',{name:'Activate account'}).click();const activated=await activatedResponse;output.push({step:'UI activation',http:activated.status(),body:await activated.json()});await page.getByText('Your account is active.').waitFor({timeout:20000});
await page.goto(base+'/login',{waitUntil:'networkidle'});await page.locator('input[autocomplete="organization"]').fill('acme');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('ActivationPass123');const loginResponse=page.waitForResponse(r=>r.url().includes('/identity/login'),{timeout:20000});await page.getByRole('button',{name:'Sign in',exact:true}).click();const signed=await loginResponse;output.push({step:'UI activated user login',http:signed.status()});await page.waitForURL(/\/app\/home/,{timeout:20000});
await page.goto(base+'/forgot-password',{waitUntil:'networkidle'});await page.getByLabel('Workspace',{exact:true}).fill('acme');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByRole('button',{name:'Send reset link'}).click();await page.getByRole('link',{name:'Open link'}).waitFor({timeout:20000});await page.getByRole('link',{name:'Open link'}).click();await page.waitForLoadState('networkidle');await page.getByLabel('New password',{exact:true}).fill('EmployeeReset123');await page.getByLabel('Confirm password',{exact:true}).fill('EmployeeReset123');const resetResponse=page.waitForResponse(r=>r.url().includes('/identity/reset-password'),{timeout:20000});await page.getByRole('button',{name:'Reset password'}).click();const reset=await resetResponse;output.push({step:'UI password reset',http:reset.status()});await page.getByText('Password reset complete.').waitFor({timeout:20000});await page.getByRole('link',{name:'Sign in',exact:true}).click();await page.waitForLoadState('networkidle');await page.locator('input[autocomplete="organization"]').fill('acme');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('EmployeeReset123');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(/\/app\/home/,{timeout:20000});output.push({step:'Reset user login',status:'PASS',url:page.url()});
}catch(e){output.push({step:'Failure',status:'FAIL',message:e.message,url:page.url(),screen:(await page.locator('body').innerText()).slice(-1600)});await page.screenshot({path:'reports/qa-2026-10-06/auth-retest.png',fullPage:true});}
fs.writeFileSync('reports/qa-2026-10-06/auth-retest.json',JSON.stringify(output,null,2));console.log(output.map(x=>({step:x.step,status:x.status,http:x.http,message:x.message})));await browser.close();

