import fs from 'node:fs';
const base='http://localhost:3121/api/v1';const results=[];
async function login(email){const r=await fetch(base+'/identity/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({workspace:'acme',email,password:'password123'})});return (await r.json()).data.token;}
const employee=await login('employee@acme.test');const admin=await login('admin@acme.test');
async function req(name,token,method,path,data,expected){const r=await fetch(base+path,{method,headers:{authorization:'Bearer '+token,'content-type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});const body=await r.json();results.push({name,method,path,input:data,http:r.status,expected,result:body,status:expected.includes(r.status)?'PASS':'FAIL'});return body.data;}
const entities=await req('employee entity scope',employee,'GET','/entities',null,[200]);const entity=entities[0].id;const stamp=Date.now();
const trip={name:'QA input '+stamp,legalEntityId:entity,destination:'Chicago',origin:'SFO',purpose:'QA input validation',startDate:'2026-11-10',endDate:'2026-11-12',estimatedAmount:'100',currency:'USD'};
for(const [name,patch] of [['negative amount',{estimatedAmount:'-1'}],['zero amount',{estimatedAmount:'0'}],['invalid money',{estimatedAmount:'abc'}],['excess precision',{estimatedAmount:'1.234'}],['bad currency',{currency:'XYZ'}],['reverse dates',{startDate:'2026-11-15'}],['invalid date',{startDate:'bad-date'}],['blank destination',{destination:''}],['blank name',{name:''}],['past trip',{startDate:'2020-01-01',endDate:'2020-01-02'}]])await req('travel '+name,employee,'POST','/travel',{...trip,...patch},[400,422]);
const created=await req('travel valid trip',employee,'POST','/travel',trip,[200,201]);
if(created){const search=await req('travel flight search',employee,'POST',`/travel/${created.id}/search`,{type:'FLIGHT'},[200]);const oop=search.quotes.find(q=>q.outOfPolicy)||search.quotes[0];await req('travel quote tamper amount and policy',employee,'POST',`/travel/${created.id}/select-quote`,{...oop,amount:'0.01',outOfPolicy:false,policyResult:'PASS'},[400,403,409,422]);await req('travel fabricated quote',employee,'POST',`/travel/${created.id}/select-quote`,{quoteId:'fabricated-qa-quote',type:'FLIGHT',supplier:'Fake QA Airline',amount:'1',currency:'USD',outOfPolicy:false,policyResult:'PASS'},[400,404,422]);await req('travel submit',employee,'POST',`/travel/${created.id}/submit`,{},[200]);await req('travel self approval blocked',employee,'POST',`/travel/${created.id}/approve`,{},[403]);}
await req('employee accounting denied',employee,'GET','/accounting',null,[403]);await req('employee payment creation denied',employee,'POST','/payments',{billId:'fake',amount:'1',rail:'ACH',idempotencyKey:'qa'},[403]);await req('unauthenticated people denied','invalid','GET','/people',null,[401]);
fs.writeFileSync('reports/qa-2026-10-06/input-probes.json',JSON.stringify(results,null,2));console.log(results.map(r=>({name:r.name,http:r.http,status:r.status,result:r.result?.error?.code}))); 
