import fs from 'node:fs';import {chromium} from 'playwright';
const base='http://localhost:3122';const output=[];const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext();
async function call(token,method,path,data){const r=await context.request.fetch(base+'/api/v1'+path,{method,headers:{authorization:'Bearer '+token},...(data?{data}:{})});const body=await r.json();if(!r.ok())throw new Error(method+' '+path+' '+r.status()+' '+JSON.stringify(body));return body.data;}
async function login(email){const r=await context.request.post(base+'/api/v1/identity/login',{data:{email,password:'password123',workspace:'acme'}});return (await r.json()).data.token;}
const employee=await login('employee@acme.test'),manager=await login('manager@acme.test'),admin=await login('admin@acme.test');
try{const entity=(await call(employee,'GET','/entities'))[0];const stamp=Date.now();const trip=await call(employee,'POST','/travel',{name:'QA complete journey '+stamp,legalEntityId:entity.id,destination:'Chicago',origin:'SFO',purpose:'QA customer visit',startDate:'2026-11-10',endDate:'2026-11-12',estimatedAmount:'900',currency:'USD'});
const {quotes}=await call(employee,'POST',`/travel/${trip.id}/search`,{type:'FLIGHT'});const quote=quotes.find(q=>!q.outOfPolicy);const {booking}=await call(employee,'POST',`/travel/${trip.id}/select-quote`,quote);const submitted=await call(employee,'POST',`/travel/${trip.id}/submit`,{});output.push({step:'submit',status:submitted.trip.status,requiresApproval:submitted.requiresApproval});
await call(manager,'POST',`/travel/${trip.id}/approve`,{});await call(admin,'POST',`/travel/${trip.id}/approve`,{});const held=await call(employee,'POST',`/travel-bookings/${booking.id}/book-mock`,{skipReprice:true,idempotencyKey:'qa-full-'+stamp});const confirmed=await call(employee,'POST',`/travel-bookings/${booking.id}/confirm`,{});output.push({step:'approval, booking, confirmation',status:confirmed.booking.status,hold:held.status,fund:confirmed.fund?.id,card:confirmed.card?.id});
await context.addInitScript(token=>localStorage.setItem('finance.token',token),admin);const page=await context.newPage();await page.goto(base+'/app/spend/cards/'+confirmed.card.id,{waitUntil:'networkidle'});await page.getByLabel('Amount').last().fill('25.00');await page.getByLabel('Merchant',{exact:true}).fill('QA Airline '+stamp);await page.getByLabel('Merchant category').fill('airlines');await page.getByRole('button',{name:'Authorize',exact:true}).click();await page.getByRole('status').filter({hasText:'authorization recorded'}).waitFor();await page.getByRole('button',{name:'Capture',exact:true}).first().click();await page.getByRole('status').filter({hasText:'capture completed'}).waitFor();await page.screenshot({path:'reports/qa-2026-10-06/supplemental-capture.png',fullPage:true});output.push({step:'UI amount/merchant/MCC authorize and capture',status:'PASS'});
const txns=await call(admin,'GET','/transactions');const txn=txns.find(t=>t.cardId===confirmed.card.id&&t.merchant==='QA Airline '+stamp);const expenses=await call(admin,'GET','/expenses');const expense=expenses.find(e=>e.transactionId===txn?.id);if(!expense)throw new Error('Matching capture expense missing');await call(admin,'POST',`/expenses/${expense.id}/update-memo`,{memo:'QA receipt verified travel customer visit'});await call(admin,'POST',`/expenses/${expense.id}/submit`,{});await call(manager,'POST',`/expenses/${expense.id}/approve`,{});const entries=await call(admin,'GET','/accounting');const entry=entries.find(e=>e.sourceId===txn.id);if(!entry)throw new Error('Matching accounting entry missing');await call(admin,'POST',`/accounting/${entry.id}/code`,{category:'Travel',memo:'QA complete journey'});await call(admin,'POST',`/accounting/${entry.id}/ready`,{});await call(admin,'POST',`/accounting/${entry.id}/sync`,{});const after=await call(admin,'GET','/accounting/'+entry.id);output.push({step:'matching expense approval and accounting mock ERP sync',status:after.status,transactionId:txn.id,expenseId:expense.id,entryId:entry.id});
const cancelled=await call(employee,'POST',`/travel-bookings/${booking.id}/cancel`,{});const refunded=await call(employee,'POST',`/travel-bookings/${booking.id}/refund`,{});output.push({step:'booking cancel/refund',cancelStatus:cancelled.status,status:refunded.booking.status});
}catch(e){output.push({step:'failure',status:'FAIL',message:e.message});}finally{fs.writeFileSync('reports/qa-2026-10-06/supplemental-flow.json',JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));await browser.close();}
